export default {
  // Auth
  SPLASH: 'SPLASH',
  ONBOARD: 'ONBOARD',
  LOGIN: 'LOGIN',
  SIGNUP_CUSTOMER: 'SIGNUP_CUSTOMER',
  FORGET_PASSWORLD: 'FORGET_PASSWORLD',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',

  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
  DASHBOARD: 'DASHBOARD',
  ORDER_HISTORY: 'ORDER_HISTORY',
  CHAT: 'CHAT',
  MAIL: 'MAIL',
  PROFILE: 'PROFILE',
};
