export default {
  // Auth
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
  DASHBOARD: 'DASHBOARD',
  ORDER_HISTORY: 'ORDER_HISTORY',
  CHAT: 'CHAT',
  MAIL: 'MAIL',
  PROFILE: 'PROFILE',
};
