export const SUPPORT = 'SUPPORT';
export const ACCOUNT_REALTED_ISSUES = 'ACCOUNT_REALTED_ISSUES';
export const BRANCHES = 'BRANCHES';
export const PRODUCTS = 'PRODUCTS';
export const BUSINESS_PROFILE = 'BUSINESS_PROFILE';
